"""initial schema

Revision ID: 44cee7cc8337
Revises: 
Create Date: 2026-03-11 23:01:31.477699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '44cee7cc8337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'HANDED_OFF', 'FAILED', name='callstatus'), nullable=False),
    sa.Column('caller_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_external_id'), 'call_sessions', ['external_id'], unique=True)
    op.create_table('call_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('UTTERANCE_RECEIVED', 'INTENT_PREDICTED', 'POLICY_CHECKED', 'DECISION_MADE', 'HANDOFF_CREATED', 'DOWNSTREAM_CALLED', name='eventtype'), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_session_id'), 'call_events', ['call_session_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('CONTINUE', 'CLARIFY', 'FALLBACK', 'HANDOFF', name='decisiontype'), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_call_session_id'), 'decision_records', ['call_session_id'], unique=False)
    op.create_table('handoff_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_summaries_call_session_id'), 'handoff_summaries', ['call_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoff_summaries_call_session_id'), table_name='handoff_summaries')
    op.drop_table('handoff_summaries')
    op.drop_index(op.f('ix_decision_records_call_session_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_call_events_call_session_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_call_sessions_external_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
